name: Deploy Jamel-test

on:
  push:
    branches: main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  AWS_ECR: ${{ secrets.AWS_ECR }}

  IMAGE: jamel-test

  AWS_REGION: ${{ secrets.AWS_REGION }}


jobs:
  deploy:
    name: Build & Notify Humanitec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag with SHA
        run: echo "TAG=`echo $GITHUB_SHA | cut -c 1-7`" >> $GITHUB_ENV

      - run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login \
                --username AWS \
                --password-stdin \
                $AWS_ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: docker build --platform linux/amd64 . -t $AWS_ECR/$IMAGE:$TAG
      - run: docker push $AWS_ECR/$IMAGE:$TAG

      - name: Inform Humanitec
        run: |-
          curl \
            --request POST 'https://api.humanitec.io/orgs/${{ secrets.HUMANITEC_ORG_ID }}/images/myapp/builds' \
            --header 'Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "branch": "'$GITHUB_REF_NAME'",
                "commit": "'$GITHUB_SHA'",
                "image": "'$AWS_ECR/$IMAGE:$TAG'",
                "tags": ["'$TAG'"]
            }'
      - name: Deploy using Score
        run: |
          wget https://github.com/score-spec/score-humanitec/releases/download/0.4.0/score-humanitec_0.4.0_linux_amd64.tar.gz
          tar -xvzf ./score-humanitec_0.4.0_linux_amd64.tar.gz

          cat <<EOF > overrides.score.yaml
          apiVersion: score.dev/v1b1
          containers:
            frontend:
              image: $AWS_ECR/$IMAGE:$TAG
          EOF

          ./score-humanitec delta --env development --app jamel-test --org="${{ secrets.HUMANITEC_ORG_ID }}" --token "${{ secrets.HUMANITEC_TOKEN }}" --deploy

